tehou:
    api:
        enabled: true
        token: "UN_TOKEN_API_SECRET_A_CHANGER"
    debug:
        enabled: true
        token: "DEBUG_TOKEN_CHANGE_IN_PROD"
    syslog:
        batch_size: 1000
        max_processing_time: 300 # 5 minutes max
        max_errors: 100
        regex_patterns:
            connection:
                - '/port\s+(\w+\/\d+\/\d+).*port\s+ID\s+is\s+([\w-]+)/'
                - '/interface\s+(\w+\d+\/\d+).*MAC:\s*([a-fA-F0-9:-]+)/'
            disconnection:
                - '/interface\s+(\w+\/\d+\/\d+).*changed\s+to\s+down/'
                - '/port\s+(\w+\/\d+\/\d+).*Physical\s+state.*down/'
